# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d248b43448b9042145379aaa1ebd9feb83bc6b45d5a905648a0b7339f9815e3d3d187a7d98251c2b66fd1e2323bf98513f6a586c295536e086a9f0ee6122d1f5

test:
  secret_key_base: 276c37bf850a82f2a637ddf65c0aef7fe9a1b1231d9c3da1ad8bdbead8c4bce37f551713b52e585e383b6c31c70bb4ebcc1e266488dfdfc8c7e8936a24eb9390

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
